services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - suraksheet-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - suraksheet-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: ["/usr/bin/init-minio.sh"]
    volumes:
      - minio-data:/data
      - ./init-minio.sh:/usr/bin/init-minio.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - suraksheet-network

  backend:
    build:
      context: ./suraksheet-backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      RABBITMQ_URL: ${RABBITMQ_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    depends_on:
      - mysql
      - rabbitmq
      - minio
      - extractor
    ports:
      - "8080:8080"
    networks:
      - suraksheet-network

  extractor:
    build:
      context: ./suraksheet-extractor
      dockerfile: Dockerfile
    container_name: extractor
    volumes:
      - ./suraksheet-extractor/main.py:/app/main.py
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      RABBITMQ_URL: ${RABBITMQ_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_started
    networks:
      - suraksheet-network

  # frontend:
  #   build:
  #     context: ./suraksheet-frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "5173:5173"
  #   networks:
  #     - suraksheet-network

volumes:
  mysql-data:
  minio-data:

networks:
  suraksheet-network:
